FROM finkandreas/utopia:stage03
MAINTAINER Andreas Fink <andreas.fink@cscs.ch>

COPY buildscripts /tmp/buildscripts
SHELL ["/bin/bash", "-c"]
RUN source scl_source enable devtoolset-7 \
    && source /opt_scientific/libs/environment \
    &&/tmp/buildscripts/build_cpu.sh /tmp/build /opt_scientific/libs 4 \
    && rm -Rf /tmp/build
